jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./public/  // CHANGE THAT TO WHATEVER YOU WANT
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
